//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninject.Tools.NuGetPackager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ninject.Tools.NuGetPackager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] Ninject {
            get {
                object obj = ResourceManager.GetObject("Ninject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_bbvEventBroker {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_bbvEventBroker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_ChildKernel {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_ChildKernel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_ContextPreservation {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_ContextPreservation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_Conventions {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_Conventions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_DependencyCreation {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_DependencyCreation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_Interception {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_Interception", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_Logging {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_Logging", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_MessageBroker {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_MessageBroker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_NamedScope {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_NamedScope", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_Wcf {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_Wcf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_WeakEventMessageBroker {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_WeakEventMessageBroker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_Wf {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_Wf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Extensions_Xml {
            get {
                object obj = ResourceManager.GetObject("Ninject_Extensions_Xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_MockingKernel {
            get {
                object obj = ResourceManager.GetObject("Ninject_MockingKernel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Web {
            get {
                object obj = ResourceManager.GetObject("Ninject_Web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Web_Mvc_FluentValidation {
            get {
                object obj = ResourceManager.GetObject("Ninject_Web_Mvc_FluentValidation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Web_Mvc1 {
            get {
                object obj = ResourceManager.GetObject("Ninject_Web_Mvc1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Web_Mvc2 {
            get {
                object obj = ResourceManager.GetObject("Ninject_Web_Mvc2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject_Web_Mvc3 {
            get {
                object obj = ResourceManager.GetObject("Ninject_Web_Mvc3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Ninject1 {
            get {
                object obj = ResourceManager.GetObject("Ninject1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
